# -*- coding: utf-8 -*-
"""RISHIDIN_homework_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H1EF0cRGYjqHXEeYhty2ZKZbtYt77tZP
"""

def findChar(a:str,b:int):
  if type(a) is not str or type(b) is not int:
    return "A must be string and b must be an integer"
  else:
    bth_char = a[b-1]
    print(bth_char)

findChar("rishi",5)

import math
def doMath(c,d,e):
  x = e.count(d) 
  ans=c*c*c+(c/0.65)+x
  ans=math.floor(ans)          
  return ans

doMath (3, "w", [1, "w", "w", 9])

import csv
def fileInfo(f):
    with open(f, newline='') as file:
        read_csv = csv.reader(file)
        R = len(list(read_csv ))
        file.seek(0)
        C = len(next(read_csv ))
    return [R, C]

fileInfo("/practice.csv")